name: deploy myblog

on:
  push:
    branches:
      - 'main' # 针对 main 分支
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'bin/*'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # 第三的 action

      - name: create a folder
        run: mkdir test-folder

      - name: touch a file
      run: |
        cd test-folder
        touch a.txt
        echo "hello world" > a.txt
        cat a.txt

      - name: delete a file
        run: rm -rf a.txt